#%RAML 1.0
---
#===============================================================
#  References:
#    - RAML Specification - https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md
#===============================================================
title: campaign Upload
uses: 
  traits: lib/traits/traits.raml
version: v1
baseUri: "/{version}"
mediaType:  application/json
protocols: [ HTTP, HTTPS ]
types:
  postPartnerOffersResponseObject: !include schemas/body/post-partner-offers.json

  getPartnerOffersResponseObject: !include schemas/body/get-partner-offers.json
  partnerOffer: !include schemas/body/partner-offer.json
  headers: !include schemas/body/headers.json
  header: !include schemas/body/header.json
  data: !include schemas/body/data.json
#===============================================================
# API resource definitions
#===============================================================
/partner-offers:
  post:
    body:
      multipart/form-data:
        properties:
          file:
            description: The file to be uploaded
            required: true
            type: file 
          uploadedBy:
            description: The name of uploader
            required: true
            type: string
    responses:
        200:
            description: request to create item accepted
            body:
              application/json:
                schema: postPartnerOffersResponseObject
                example: !include examples/body/example-post-partner-offers.json
                
  get:
    responses:
        200:
            body:
                application/json:
                    schema: getPartnerOffersResponseObject
                    example: !include examples/body/example-get-partner-offers.json