ALTER TABLE `corporate_offer_staging` DROP CONSTRAINT `CORPORATE_OFFER_STAGING_FILE_MASTER_FK`;
ALTER TABLE `partner_offer_staging` DROP CONSTRAINT `PARTNER_OFFER_STAGING_FILE_MASTER_FK`;
ALTER TABLE `cmp_staging` DROP CONSTRAINT `CMP_STAGING_FILE_MASTER_FK`;

DROP TABLE IF EXISTS `file_master`;
